import { ActivityType, ClientSource, LeadTemperature, PropertyStatus } from "../src/generated/prisma/client.js";
import type { DefaultStage } from "../src/modules/pipelines/default-stages.js";

export const RENTAL_STAGES: DefaultStage[] = [
  { name: "Interessado", position: 0 },
  { name: "Documentação", position: 1 },
  { name: "Vistoria", position: 2 },
  { name: "Contrato assinado", position: 3, isWon: true },
  { name: "Desistiu", position: 4, isLost: true },
];

export const properties = [
  {
    title: "Apartamento 3 quartos — Gleba Palhano",
    type: "Apartamento",
    address: "Rua Fernando de Noronha, 1200 — Gleba Palhano",
    price: 890000,
    bedrooms: 3,
    area: 118,
    status: PropertyStatus.DISPONIVEL,
  },
  {
    title: "Casa em condomínio — Aurora",
    type: "Casa",
    address: "Alameda dos Ipês, 340 — Condomínio Aurora",
    price: 1250000,
    bedrooms: 4,
    area: 260,
    status: PropertyStatus.DISPONIVEL,
  },
  {
    title: "Apartamento 2 quartos — Centro",
    type: "Apartamento",
    address: "Av. Higienópolis, 785 — Centro",
    price: 420000,
    bedrooms: 2,
    area: 74,
    status: PropertyStatus.RESERVADO,
  },
  {
    title: "Cobertura duplex — Bela Suíça",
    type: "Cobertura",
    address: "Rua Piauí, 90 — Bela Suíça",
    price: 1780000,
    bedrooms: 4,
    area: 310,
    status: PropertyStatus.DISPONIVEL,
  },
  {
    title: "Sobrado — Jardim Higienópolis",
    type: "Sobrado",
    address: "Rua Tupinambá, 512 — Jardim Higienópolis",
    price: 735000,
    bedrooms: 3,
    area: 180,
    status: PropertyStatus.VENDIDO,
  },
  {
    title: "Studio mobiliado — Centro",
    type: "Studio",
    address: "Rua Sergipe, 44 — Centro",
    price: 285000,
    bedrooms: 1,
    area: 38,
    status: PropertyStatus.DISPONIVEL,
  },
  {
    title: "Terreno 450m² — Vale dos Tucanos",
    type: "Terreno",
    address: "Rua das Perdizes, s/n — Vale dos Tucanos",
    price: 390000,
    bedrooms: null,
    area: 450,
    status: PropertyStatus.DISPONIVEL,
  },
  {
    title: "Sala comercial — Shopping Catuaí",
    type: "Comercial",
    address: "Av. Madre Leônia Milito, 1550 — Sala 812",
    price: 560000,
    bedrooms: null,
    area: 62,
    status: PropertyStatus.INATIVO,
  },
  {
    title: "Casa térrea — Jardim Bandeirantes",
    type: "Casa",
    address: "Rua Antônio Rodrigues, 226 — Jardim Bandeirantes",
    price: 610000,
    bedrooms: 3,
    area: 155,
    status: PropertyStatus.DISPONIVEL,
  },
  {
    title: "Apartamento 1 quarto — Vila Ipiranga",
    type: "Apartamento",
    address: "Rua Belo Horizonte, 318 — Vila Ipiranga",
    price: 245000,
    bedrooms: 1,
    area: 45,
    status: PropertyStatus.DISPONIVEL,
  },
];

export const clients = [
  {
    name: "Carlos Silva",
    email: "carlos.silva@email.com",
    phone: "(43) 99812-4470",
    source: ClientSource.SITE,
    notes: "Procura 3 quartos na Gleba Palhano, financiamento pela Caixa aprovado.",
    description:
      "Casal com dois filhos em idade escolar.\nQuer ficar perto do colégio na Gleba Palhano e não abre mão de duas vagas.",
    tags: ["financiamento", "gleba-palhano"],
    temperature: LeadTemperature.QUENTE,
    interestType: "Apartamento",
    budgetMin: 800000,
    budgetMax: 900000,
  },
  {
    name: "Mariana Costa",
    email: "mariana.costa@email.com",
    phone: "(43) 99745-1183",
    source: ClientSource.INSTAGRAM,
    notes: "Primeiro imóvel, entrada de R$ 80 mil.",
    description: "Primeiro imóvel, entrada de R$ 80 mil já aprovada no banco.",
    tags: ["primeiro-imovel"],
    temperature: LeadTemperature.MORNO,
    interestType: "Apartamento",
    budgetMin: 380000,
    budgetMax: 450000,
  },
  {
    name: "Lucas Almeida",
    email: "lucas.almeida@email.com",
    phone: "(43) 99630-2277",
    source: ClientSource.INDICACAO,
    notes: "Indicado pelo Roberto Menezes. Quer casa em condomínio fechado.",
    description: "Indicado pelo Roberto Menezes. Quer casa em condomínio fechado, com segurança 24h.",
    tags: ["condominio-fechado", "indicacao"],
    temperature: LeadTemperature.QUENTE,
    interestType: "Casa",
    budgetMin: 1100000,
    budgetMax: 1300000,
  },
  {
    name: "Ana Pereira",
    email: "ana.pereira@email.com",
    phone: "(43) 99521-6690",
    source: ClientSource.WHATSAPP,
    notes: null,
  },
  {
    name: "Roberto Menezes",
    email: "roberto.menezes@email.com",
    phone: "(43) 99418-3352",
    source: ClientSource.INDICACAO,
    notes: "Investidor, compra para locação. Já fechou duas vezes com a casa.",
  },
  {
    name: "Fernanda Lima",
    email: "fernanda.lima@email.com",
    phone: "(43) 99307-8821",
    source: ClientSource.SITE,
    notes: "Trabalha em home office, prioriza um cômodo extra para escritório.",
  },
  {
    name: "Paulo Ribeiro",
    email: "paulo.ribeiro@email.com",
    phone: "(43) 99284-5514",
    source: ClientSource.OUTROS,
    notes: "Veio pelo anúncio no jornal.",
  },
  {
    name: "Juliana Tavares",
    email: "juliana.tavares@email.com",
    phone: "(43) 99176-9903",
    source: ClientSource.INSTAGRAM,
    notes: "Quer studio no Centro para alugar, orçamento apertado.",
    description: "Desistiu da compra e migrou para locação. Quer studio no Centro, orçamento apertado.",
    tags: ["locacao"],
    temperature: LeadTemperature.FRIO,
    interestType: "Studio",
    budgetMin: 1800,
    budgetMax: 2400,
  },
  {
    name: "Marcos Vinícius Duarte",
    email: "marcos.duarte@email.com",
    phone: "(43) 99065-4432",
    source: ClientSource.WHATSAPP,
    notes: null,
  },
  {
    name: "Beatriz Nogueira",
    email: "beatriz.nogueira@email.com",
    phone: "(43) 98954-7718",
    source: ClientSource.SITE,
    notes: "Mudança de cidade em três meses, prazo curto.",
  },
  {
    name: "Rafael Antunes",
    email: "rafael.antunes@email.com",
    phone: "(43) 98843-2265",
    source: ClientSource.INDICACAO,
    notes: "Vendeu o apartamento antigo, compra à vista.",
  },
  {
    name: "Camila Ferraz",
    email: "camila.ferraz@email.com",
    phone: "(43) 98732-1109",
    source: ClientSource.INSTAGRAM,
    notes: null,
  },
  {
    name: "Diego Moraes",
    email: "diego.moraes@email.com",
    phone: "(43) 98621-8876",
    source: ClientSource.WHATSAPP,
    notes: "Interessado em terreno para construir.",
  },
  {
    name: "Patrícia Salles",
    email: "patricia.salles@email.com",
    phone: "(43) 98510-3341",
    source: ClientSource.OUTROS,
    notes: "Cliente antiga da carteira, voltou a procurar.",
  },
  {
    name: "Sérgio Bonini",
    email: "sergio.bonini@email.com",
    phone: "(43) 98409-5567",
    source: ClientSource.SITE,
    notes: null,
  },
  {
    name: "Larissa Meneghel",
    email: "larissa.meneghel@email.com",
    phone: "(43) 98398-2214",
    source: ClientSource.INSTAGRAM,
    notes: "Chegou pelo anúncio do apartamento no Centro.",
  },
  {
    name: "Otávio Prado",
    email: "otavio.prado@email.com",
    phone: "(43) 98287-6640",
    source: ClientSource.WHATSAPP,
    notes: null,
  },
  {
    name: "Helena Ruiz",
    email: "helena.ruiz@email.com",
    phone: "(43) 98176-3398",
    source: ClientSource.INDICACAO,
    notes: "Indicada pela Fernanda Lima.",
  },
];

/**
 * `stage` é o nome do estágio dentro do pipeline indicado — os ids saem da criação, e casar por
 * nome mantém os dados legíveis aqui sem precisar de fixtures de id.
 */
type DealSeed = {
  client: string;
  property: string | null;
  stage: string;
  title: string;
  value: number;
  lostReason?: string;
  createdDaysAgo: number;
};

export const salesDeals: DealSeed[] = [
  {
    client: "Carlos Silva",
    property: "Apartamento 3 quartos — Gleba Palhano",
    stage: "Proposta",
    title: "Apartamento Gleba Palhano — Carlos Silva",
    value: 869000,
    createdDaysAgo: 34,
  },
  {
    client: "Lucas Almeida",
    property: "Casa em condomínio — Aurora",
    stage: "Visita",
    title: "Casa Aurora — Lucas Almeida",
    value: 1250000,
    createdDaysAgo: 21,
  },
  {
    client: "Mariana Costa",
    property: "Apartamento 2 quartos — Centro",
    stage: "Qualificado",
    title: "Apartamento Centro — Mariana Costa",
    value: 415000,
    createdDaysAgo: 17,
  },
  {
    client: "Ana Pereira",
    property: "Apartamento 1 quarto — Vila Ipiranga",
    stage: "Contato",
    title: "Apartamento Vila Ipiranga — Ana Pereira",
    value: 245000,
    createdDaysAgo: 9,
  },
  {
    client: "Roberto Menezes",
    property: "Sobrado — Jardim Higienópolis",
    stage: "Fechado",
    title: "Sobrado Higienópolis — Roberto Menezes",
    value: 720000,
    createdDaysAgo: 62,
  },
  {
    client: "Fernanda Lima",
    property: "Casa térrea — Jardim Bandeirantes",
    stage: "Proposta",
    title: "Casa Bandeirantes — Fernanda Lima",
    value: 598000,
    createdDaysAgo: 28,
  },
  {
    client: "Paulo Ribeiro",
    property: "Sala comercial — Shopping Catuaí",
    stage: "Perdido",
    title: "Sala comercial Catuaí — Paulo Ribeiro",
    value: 560000,
    lostReason: "Fechou com a concorrência por um valor abaixo do nosso mínimo.",
    createdDaysAgo: 47,
  },
  {
    client: "Beatriz Nogueira",
    property: "Cobertura duplex — Bela Suíça",
    stage: "Visita",
    title: "Cobertura Bela Suíça — Beatriz Nogueira",
    value: 1740000,
    createdDaysAgo: 13,
  },
  {
    client: "Rafael Antunes",
    property: "Apartamento 3 quartos — Gleba Palhano",
    stage: "Qualificado",
    title: "Apartamento Gleba Palhano — Rafael Antunes",
    value: 890000,
    createdDaysAgo: 11,
  },
  {
    client: "Camila Ferraz",
    property: null,
    stage: "Novo lead",
    title: "Busca apartamento 2 quartos — Camila Ferraz",
    value: 400000,
    createdDaysAgo: 4,
  },
  {
    client: "Diego Moraes",
    property: "Terreno 450m² — Vale dos Tucanos",
    stage: "Novo lead",
    title: "Terreno Vale dos Tucanos — Diego Moraes",
    value: 390000,
    createdDaysAgo: 3,
  },
  {
    client: "Patrícia Salles",
    property: null,
    stage: "Novo lead",
    title: "Retomada de carteira — Patrícia Salles",
    value: 500000,
    createdDaysAgo: 2,
  },
  {
    client: "Marcos Vinícius Duarte",
    property: "Casa térrea — Jardim Bandeirantes",
    stage: "Contato",
    title: "Casa Bandeirantes — Marcos Duarte",
    value: 610000,
    createdDaysAgo: 6,
  },
  {
    client: "Juliana Tavares",
    property: "Studio mobiliado — Centro",
    stage: "Perdido",
    title: "Studio Centro (compra) — Juliana Tavares",
    value: 285000,
    lostReason: "Orçamento não fechou; migrou para locação.",
    createdDaysAgo: 38,
  },
  {
    client: "Carlos Silva",
    property: "Apartamento 2 quartos — Centro",
    stage: "Fechado",
    title: "Apartamento Centro (investimento) — Carlos Silva",
    value: 398000,
    createdDaysAgo: 84,
  },
  {
    client: "Sérgio Bonini",
    property: null,
    stage: "Novo lead",
    title: "Busca sobrado até R$ 700 mil — Sérgio Bonini",
    value: 700000,
    createdDaysAgo: 2,
  },
  {
    client: "Larissa Meneghel",
    property: "Apartamento 2 quartos — Centro",
    stage: "Novo lead",
    title: "Apartamento Centro — Larissa Meneghel",
    value: 430000,
    createdDaysAgo: 1,
  },
  {
    client: "Otávio Prado",
    property: "Studio mobiliado — Centro",
    stage: "Novo lead",
    title: "Studio para investimento — Otávio Prado",
    value: 290000,
    createdDaysAgo: 1,
  },
  {
    client: "Helena Ruiz",
    property: "Casa em condomínio — Aurora",
    stage: "Contato",
    title: "Casa Aurora — Helena Ruiz",
    value: 1180000,
    createdDaysAgo: 7,
  },
];

export const rentalDeals: DealSeed[] = [
  {
    client: "Juliana Tavares",
    property: "Studio mobiliado — Centro",
    stage: "Documentação",
    title: "Locação studio Centro — Juliana Tavares",
    value: 2100,
    createdDaysAgo: 12,
  },
  {
    client: "Patrícia Salles",
    property: "Apartamento 1 quarto — Vila Ipiranga",
    stage: "Interessado",
    title: "Locação Vila Ipiranga — Patrícia Salles",
    value: 1650,
    createdDaysAgo: 5,
  },
  {
    client: "Roberto Menezes",
    property: "Sala comercial — Shopping Catuaí",
    stage: "Vistoria",
    title: "Locação sala comercial — Roberto Menezes",
    value: 3800,
    createdDaysAgo: 19,
  },
];

/**
 * `dueInDays` negativo é passado. A agenda só lista atividade com `dueAt` (agenda.repo.ts), então
 * todas trazem data; `done` separa histórico de pendência.
 */
type ActivitySeed = {
  client: string;
  deal?: string;
  type: ActivityType;
  description: string;
  dueInDays: number;
  atHour: number;
  done: boolean;
};

export const activities: ActivitySeed[] = [
  {
    client: "Carlos Silva",
    deal: "Apartamento Gleba Palhano — Carlos Silva",
    type: ActivityType.PROPOSAL,
    description: "Enviar proposta revisada com o desconto aprovado pelo proprietário",
    dueInDays: 0,
    atHour: 9,
    done: false,
  },
  {
    client: "Lucas Almeida",
    deal: "Casa Aurora — Lucas Almeida",
    type: ActivityType.VISIT,
    description: "Visita à casa do condomínio Aurora com a esposa",
    dueInDays: 0,
    atHour: 15,
    done: false,
  },
  {
    client: "Mariana Costa",
    deal: "Apartamento Centro — Mariana Costa",
    type: ActivityType.CALL,
    description: "Confirmar documentação para análise de crédito",
    dueInDays: 1,
    atHour: 10,
    done: false,
  },
  {
    client: "Beatriz Nogueira",
    deal: "Cobertura Bela Suíça — Beatriz Nogueira",
    type: ActivityType.VISIT,
    description: "Segunda visita à cobertura, agora com o arquiteto",
    dueInDays: 1,
    atHour: 17,
    done: false,
  },
  {
    client: "Fernanda Lima",
    deal: "Casa Bandeirantes — Fernanda Lima",
    type: ActivityType.PROPOSAL,
    description: "Montar contraproposta com prazo de 60 dias para desocupação",
    dueInDays: 2,
    atHour: 11,
    done: false,
  },
  {
    client: "Rafael Antunes",
    deal: "Apartamento Gleba Palhano — Rafael Antunes",
    type: ActivityType.CALL,
    description: "Apresentar as duas opções na Gleba Palhano",
    dueInDays: 2,
    atHour: 14,
    done: false,
  },
  {
    client: "Diego Moraes",
    deal: "Terreno Vale dos Tucanos — Diego Moraes",
    type: ActivityType.VISIT,
    description: "Levar ao terreno e passar o contato do engenheiro",
    dueInDays: 3,
    atHour: 9,
    done: false,
  },
  {
    client: "Camila Ferraz",
    type: ActivityType.CALL,
    description: "Levantar perfil de busca e faixa de preço",
    dueInDays: 3,
    atHour: 16,
    done: false,
  },
  {
    client: "Juliana Tavares",
    deal: "Locação studio Centro — Juliana Tavares",
    type: ActivityType.NOTE,
    description: "Cobrar comprovante de renda do fiador",
    dueInDays: 4,
    atHour: 10,
    done: false,
  },
  {
    client: "Patrícia Salles",
    type: ActivityType.CALL,
    description: "Retomar contato — carteira antiga",
    dueInDays: 5,
    atHour: 13,
    done: false,
  },
  {
    client: "Roberto Menezes",
    deal: "Locação sala comercial — Roberto Menezes",
    type: ActivityType.VISIT,
    description: "Vistoria da sala comercial com o laudo em mãos",
    dueInDays: 6,
    atHour: 8,
    done: false,
  },
  {
    client: "Sérgio Bonini",
    deal: "Busca sobrado até R$ 700 mil — Sérgio Bonini",
    type: ActivityType.CALL,
    description: "Primeiro contato — qualificar faixa de preço e região",
    dueInDays: 0,
    atHour: 11,
    done: false,
  },
  {
    client: "Larissa Meneghel",
    deal: "Apartamento Centro — Larissa Meneghel",
    type: ActivityType.CALL,
    description: "Responder o direct e agendar visita ao apartamento do Centro",
    dueInDays: 1,
    atHour: 14,
    done: false,
  },
  {
    client: "Helena Ruiz",
    deal: "Casa Aurora — Helena Ruiz",
    type: ActivityType.VISIT,
    description: "Levar à casa do Aurora junto com a Fernanda, que indicou",
    dueInDays: 4,
    atHour: 15,
    done: false,
  },
  {
    client: "Marcos Vinícius Duarte",
    deal: "Casa Bandeirantes — Marcos Duarte",
    type: ActivityType.CALL,
    description: "Retornar ligação sobre o valor do condomínio",
    dueInDays: -1,
    atHour: 11,
    done: true,
  },
  {
    client: "Ana Pereira",
    deal: "Apartamento Vila Ipiranga — Ana Pereira",
    type: ActivityType.CALL,
    description: "Primeiro contato — chegou pelo WhatsApp",
    dueInDays: -2,
    atHour: 9,
    done: true,
  },
  {
    client: "Carlos Silva",
    deal: "Apartamento Gleba Palhano — Carlos Silva",
    type: ActivityType.VISIT,
    description: "Visita ao apartamento da Gleba Palhano",
    dueInDays: -4,
    atHour: 15,
    done: true,
  },
  {
    client: "Beatriz Nogueira",
    type: ActivityType.NOTE,
    description: "Prazo de mudança confirmado para daqui a três meses",
    dueInDays: -5,
    atHour: 17,
    done: true,
  },
  {
    client: "Paulo Ribeiro",
    deal: "Sala comercial Catuaí — Paulo Ribeiro",
    type: ActivityType.NOTE,
    description: "Cliente informou que fechou com outra imobiliária",
    dueInDays: -7,
    atHour: 14,
    done: true,
  },
  {
    client: "Roberto Menezes",
    deal: "Sobrado Higienópolis — Roberto Menezes",
    type: ActivityType.PROPOSAL,
    description: "Proposta aceita — encaminhar para o cartório",
    dueInDays: -9,
    atHour: 10,
    done: true,
  },
  {
    client: "Juliana Tavares",
    deal: "Studio Centro (compra) — Juliana Tavares",
    type: ActivityType.CALL,
    description: "Cliente desistiu da compra e pediu opções de aluguel",
    dueInDays: -12,
    atHour: 16,
    done: true,
  },
];

/** `client` casa pelo nome, igual aos deals; o autor é resolvido no seed. */
export const comments = [
  {
    client: "Carlos Silva",
    body: "Proposta enviada ontem. Ele pediu 48h para conversar com a esposa.",
    daysAgo: 2,
  },
  {
    client: "Carlos Silva",
    body: "Confirmou que segue interessado; quer negociar a segunda vaga.",
    daysAgo: 1,
  },
  {
    client: "Lucas Almeida",
    body: "Visitou o Aurora e gostou. Preocupado com o valor do condomínio.",
    daysAgo: 3,
  },
  {
    client: "Juliana Tavares",
    body: "Desistiu da compra por ora. Passei as opções de locação no Centro.",
    daysAgo: 10,
  },
];
